import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
import app.routes as rt
import pytest


def test_functionality():
    assert True


colors1 = {
    "primary": "#ff0000",
    "secondary": "#00ff00",
    "accent": "#0000ff",
    "dark": "#111111",
    "bright": "#eeeeee",
    "success": "#00ff00",
    "warn": "#ffff00",
    "error": "#ff0000"
}
font1 = "Roboto"
font_provider1 = "Google"
auth_config1 = {
    "enabled": True,
    "google": True,
    "apple": False,
    "github": True,
    "keycloak": False,
    "microsoft": False,
    "discord": True,
    "facebook": False
    }
institutionname1 = "Saftladen"
institutionweb1 = "https://github.com"
topics1 = [
    {
        "name": "Test",
        "color": "#ff0001"
    }
]    
colors2 = {
    "primary": "#ff0000",
    "secondary": "#00ff00",
    "accent": "#0000ff",
    "dark": "#111111",
    "bright": "#ffffff",
    "success": "#00ff00",
    "warn": "#fffe00",
    "error": "#ff1200"
}
font2 = "Emily"
font_provider2 = "Google"
auth_config2 = {
    "enabled": False,
    "google": True,
    "apple": True,
    "github": True,
    "keycloak": False,
    "microsoft": False,
    "discord": False,
    "facebook": True
    }
institutionname2 = "Saftladen"
institutionweb2 = "https://github.com"
topics2 = [
    {
        "name": "Test",
        "color": "#ff0001"
    }
]
colors3 = {
    "primary": "#ff0000",
    "secondary": "#00ff00",
    "accent": "#0000ff",
    "dark": "#111111",
    "bright": "#eeeeee",
    "success": "#00ff00",
    "warn": "#ffff00",
    "error": "#ff0000"
}
font3 = "Roboto"
font_provider3 = "Google"
auth_config3 = {
    "enabled": True,
    "google": True,
    "apple": False,
    "github": True,
    "keycloak": False,
    "microsoft": False,
    "discord": True,
    "facebook": False
    }
institutionname3 = "Saftladen"
institutionweb3 = "https://github.com"
topics3 = [
    {
        "name": "Test",
        "color": "#ff0001"
    },
    {
        "name": "ExtraTopic",
        "color": "#00ff00"
    }
]
testvar1 = [colors1, font1, font_provider1, auth_config1, institutionname1, institutionweb1, topics1]
testvar2 = [colors2, font2, font_provider2, auth_config2, institutionname2, institutionweb2, topics2]
testvar3 = [colors3, font3, font_provider3, auth_config3, institutionname3, institutionweb3, topics3]
testerg1 = """// This file is auto-generated by Elfra Config Tool
export const config = {
  colors: {
    primary: "#ff0000",
    secondary: "#00ff00",
    accent: "#0000ff",
    dark: "#111111",
    bright: "#eeeeee",
    success: "#00ff00",
    warn: "#ffff00",
    error: "#ff0000",
  },
  font: 'Roboto',
  fontProvider: 'Google',
  auth: {
// supabase is used for authentication, so you need to set the environment variables SUPABASE_URL and SUPABASE_KEY in your .env file.
// This means you can only use Authentication, if you have set up a Supabase project.
    enabled: true,
    oAuth: {
      google: true,
      apple: false,
      github: true,
      keycloak: false,
      microsoft: false,
      discord: true,
      facebook: false,
    },
  },
  institution: {
    name: 'Saftladen',
    web: 'https://github.com',
  },
  topics: [
    { name: 'Test', color: '#ff0001' },
  ],
};"""
testerg2 = """// This file is auto-generated by Elfra Config Tool
export const config = {
  colors: {
    primary: "#ff0000",
    secondary: "#00ff00",
    accent: "#0000ff",
    dark: "#111111",
    bright: "#ffffff",
    success: "#00ff00",
    warn: "#fffe00",
    error: "#ff1200",
  },
  font: 'Emily',
  fontProvider: 'Google',
  auth: {
// supabase is used for authentication, so you need to set the environment variables SUPABASE_URL and SUPABASE_KEY in your .env file.
// This means you can only use Authentication, if you have set up a Supabase project.
    enabled: false,
  },
  institution: {
    name: 'Saftladen',
    web: 'https://github.com',
  },
  topics: [
    { name: 'Test', color: '#ff0001' },
  ],
};"""
testerg3 = """// This file is auto-generated by Elfra Config Tool
export const config = {
  colors: {
    primary: "#ff0000",
    secondary: "#00ff00",
    accent: "#0000ff",
    dark: "#111111",
    bright: "#eeeeee",
    success: "#00ff00",
    warn: "#ffff00",
    error: "#ff0000",
  },
  font: 'Roboto',
  fontProvider: 'Google',
  auth: {
// supabase is used for authentication, so you need to set the environment variables SUPABASE_URL and SUPABASE_KEY in your .env file.
// This means you can only use Authentication, if you have set up a Supabase project.
    enabled: true,
    oAuth: {
      google: true,
      apple: false,
      github: true,
      keycloak: false,
      microsoft: false,
      discord: true,
      facebook: false,
    },
  },
  institution: {
    name: 'Saftladen',
    web: 'https://github.com',
  },
  topics: [
    { name: 'Test', color: '#ff0001' },
    { name: 'ExtraTopic', color: '#00ff00' },
  ],
};"""

testcases = [
    (testvar1, testerg1), 
    (testvar2, testerg2),
    (testvar3, testerg3)
]

@pytest.mark.parametrize("testinput,expected", testcases)
def test_generatefile(testinput, expected):
    assert rt.generate_theme_ts(*testinput) == expected
    