from flask import render_template, send_file, Flask
from app.forms import ConfigForm
from io import BytesIO
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, BooleanField, FormField, FieldList
from wtforms.validators import DataRequired, Optional
from app import app





# Funktion zum Generieren des TypeScript-Codes

def generate_theme_ts(colors, font, font_provider, auth_config, institution_name, institution_web, topics):
    ts_lines = []
    ts_lines.append("// This file is auto-generated by Elfra Config Tool")
    ts_lines.append("export const config = {")
    ts_lines.append("  colors: {")
    for key, value in colors.items():
        ts_lines.append(f'    {key}: "{value}",')
    ts_lines.append("  },")
    ts_lines.append(f"  font: '{font}',")
    ts_lines.append(f"  fontProvider: '{font_provider}',")
    ts_lines.append("  auth: {")
    for key, value in auth_config.items():
        ts_lines.append(f"    {key}: {str(value).lower()},")
    ts_lines.append("  },")
    ts_lines.append("  institution: {")
    ts_lines.append(f"    name: '{institution_name}',")
    ts_lines.append(f"    web: '{institution_web}',")
    ts_lines.append("  },")
    ts_lines.append("  topics: [")
    for topic in topics:
        ts_lines.append(f"    {{ name: '{topic['name']}', color: '{topic['color']}' }},")
    ts_lines.append("  ],")
    ts_lines.append("};")
    return "\n".join(ts_lines)

# Flask route to handle the form submission and generate the TypeScript configuration
@app.route("/", methods=["GET", "POST"])
def index():
    form = ConfigForm()
    if form.validate_on_submit():
        
        
        # TypeScript-Code generieren
        ts_code = generate_theme_ts(
            colors,
            form.font.data,
            form.font_provider.data,
            auth_config,
            form.institution_name.data,
            form.institution_web.data,
            topics
        )
        # Datei als Download anbieten
        return send_file(
            BytesIO(ts_code.encode("utf-8")),
            mimetype="text/plain",
            as_attachment=True,
            download_name="config.ts"
        )
    return render_template("index.html", form=form)
