from flask import render_template, send_file, Flask, request
from app.forms import ConfigForm
from io import BytesIO
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, BooleanField, FormField, FieldList
from wtforms.validators import DataRequired, Optional
from app import app





# Funktion zum Generieren des TypeScript-Codes

def generate_theme_ts(colors, font, font_provider, auth_config, institution_name, institution_web, topics):
    ts_lines = []
    ts_lines.append("// This file is auto-generated by Elfra Config Tool")
    ts_lines.append("export const config = {")
    ts_lines.append("  colors: {")
    for key, value in colors.items():
        ts_lines.append(f'    {key}: "{value}",')
    ts_lines.append("  },")
    ts_lines.append(f"  font: '{font}',")
    ts_lines.append(f"  fontProvider: '{font_provider}',")
    ts_lines.append("  auth: {")
    ts_lines.append("// supabase is used for authentication, so you need to set the environment variables SUPABASE_URL and SUPABASE_KEY in your .env file.")
    ts_lines.append("// This means you can only use Authentication, if you have set up a Supabase project.")
    ts_lines.append(f"    enabled: {str(auth_config['enabled']).lower()},")
    if auth_config['enabled']:
        ts_lines.append("    oAuth: {")
        for provider in ['apple', 'google', 'github', 'keycloak', 'microsoft', 'discord', 'facebook']:
            if auth_config[provider]:
                ts_lines.append(f"      {provider}: true,")
        ts_lines.append("    },")
    ts_lines.append("  },")
    ts_lines.append("  institution: {")
    ts_lines.append(f"    name: '{institution_name}',")
    ts_lines.append(f"    web: '{institution_web}',")
    ts_lines.append("  },")
    ts_lines.append("  topics: [")
    for topic in topics:
        ts_lines.append(f"    {{ name: '{topic['name']}', color: '{topic['color']}' }},")
    ts_lines.append("  ],")
    ts_lines.append("};")
    return "\n".join(ts_lines)

# Flask route to handle the form submission and generate the TypeScript configuration
@app.route("/", methods=["GET", "POST"])
def index():
    #  Logic to handle GET and POST requests 
    #  Post request will generate TypeScript code based on the form data
    form = ConfigForm()
    #  If the form is submitted, validate it and generate the TypeScript code
    if request.method == "POST":
        print("Post startet")
        if form.validate_on_submit():
            #  Extracting form data
            colors = {
                "primary": form.primary.data,
                "secondary": form.secondary.data,
                "accent": form.accent.data,
                "dark": form.dark.data,
                "bright": form.bright.data,
                "success": form.success.data,
                "warn": form.warn.data,
                "error": form.error.data
            }
            auth_config = {
                "enabled": form.auth.enabled.data,
                "google": form.auth.google.data,
                "apple": form.auth.apple.data,
                "github": form.auth.github.data,
                "keycloak": form.auth.keycloak.data,
                "microsoft": form.auth.microsoft.data,
                "discord": form.auth.discord.data,
                "facebook": form.auth.facebook.data
            }
            institution_name = form.institution_name.data
            institution_web = form.institution_web.data
            topics = [{"name": topic.topic.data, "color": topic.color.data} for topic in form.topics.entries]
            font = form.font.data
            font_provider = form.font_provider.data
            ts_code = generate_theme_ts(colors, font, font_provider, auth_config, institution_name, institution_web, topics)
        # Nach dem Submit des TypeScript-Codes direkt als Download anbieten
            return send_file(
                BytesIO(ts_code.encode("utf-8")),
                mimetype="text/plain",
                as_attachment=True,
                download_name="config.ts"
                )
        else:
            #  If the form is not valid, render the form with errors
            return render_template("index.html", form=form, errors=form.errors)
    else:
        form.auth.enabled.data = False
        form.auth.google.data = True
        form.auth.apple.data = True
        form.auth.github.data = True
        form.auth.keycloak.data = True
        form.auth.microsoft.data = True
        form.auth.discord.data = True
        form.auth.facebook.data = True
        form.font.data = ""
        form.font_provider.data = ""
        form.institution_name.data = ""
        form.institution_web.data = ""
        form.topics.append_entry()
        form.topics.entries[0].topic = "Setup Topic"
        form.topics.entries[0].color = "#FF5733"  # Example color value

    return render_template("index.html", form=form)
